"""3

Revision ID: fbdfa2d3741f
Revises: 45c6bf94e3f5
Create Date: 2025-12-07 03:50:40.411961

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fbdfa2d3741f"
down_revision: Union[str, Sequence[str], None] = "45c6bf94e3f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "packages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("destination_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("itinerary", sa.Text(), nullable=False),
        sa.Column("max_travelers", sa.Integer(), nullable=False),
        sa.Column("contact_phone", sa.String(length=20), nullable=False),
        sa.Column("images", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["destinations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_packages_agent_id"), "packages", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_packages_destination_id"), "packages", ["destination_id"], unique=False
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("tourist_id", sa.UUID(), nullable=False),
        sa.Column("travel_date", sa.Date(), nullable=False),
        sa.Column("travelers_count", sa.Integer(), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "confirmed", "cancelled", "completed", name="booking_status"
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("has_reviewed", sa.Boolean(), nullable=True),
        sa.Column(
            "payment_status",
            sa.Enum(
                "unpaid",
                "pending_verification",
                "verified",
                "rejected",
                name="payment_status",
            ),
            nullable=False,
        ),
        sa.Column("payment_proof_url", sa.String(length=500), nullable=True),
        sa.Column("payment_proof_uploaded_at", sa.DateTime(), nullable=True),
        sa.Column("payment_verified_at", sa.DateTime(), nullable=True),
        sa.Column("payment_rejection_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tourist_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bookings_created_at"), "bookings", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_bookings_package_id"), "bookings", ["package_id"], unique=False
    )
    op.create_index(
        op.f("ix_bookings_payment_status"), "bookings", ["payment_status"], unique=False
    )
    op.create_index(op.f("ix_bookings_status"), "bookings", ["status"], unique=False)
    op.create_index(
        op.f("ix_bookings_tourist_id"), "bookings", ["tourist_id"], unique=False
    )
    op.create_index(
        op.f("ix_bookings_travel_date"), "bookings", ["travel_date"], unique=False
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("tourist_id", sa.UUID(), nullable=False),
        sa.Column("booking_id", sa.UUID(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("rating >= 1 AND rating <= 5", name="check_rating_range"),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tourist_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reviews_booking_id"), "reviews", ["booking_id"], unique=False
    )
    op.create_index(
        op.f("ix_reviews_created_at"), "reviews", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_reviews_package_id"), "reviews", ["package_id"], unique=False
    )
    op.create_index(
        op.f("ix_reviews_tourist_id"), "reviews", ["tourist_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reviews_tourist_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_package_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_created_at"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_booking_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_bookings_travel_date"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_tourist_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_status"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_payment_status"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_package_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_created_at"), table_name="bookings")
    op.drop_table("bookings")
    op.drop_index(op.f("ix_packages_destination_id"), table_name="packages")
    op.drop_index(op.f("ix_packages_agent_id"), table_name="packages")
    op.drop_table("packages")
    # ### end Alembic commands ###
