"""add qris table

Revision ID: fc9568da425b
Revises: 16ba87f19cca
Create Date: 2025-12-14 10:10:11.647596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9568da425b'
down_revision: Union[str, Sequence[str], None] = '16ba87f19cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qris',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('foto_qr_path', sa.String(length=500), nullable=False),
    sa.Column('static_qris_string', sa.String(length=500), nullable=False),
    sa.Column('dynamic_qris_string', sa.String(length=500), nullable=False),
    sa.Column('fee_type', sa.Enum('persentase', 'rupiah', name='fee_type'), nullable=True),
    sa.Column('fee_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('static_qris_string')
    )
    op.create_index(op.f('ix_qris_created_at'), 'qris', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qris_created_at'), table_name='qris')
    op.drop_table('qris')
    # ### end Alembic commands ###
